apiVersion : apps/v1
kind: Deployment
metadata:
  name: "finalcheckcluster-5b05"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "finalcheckcluster-5b05"
  template:
    metadata:
      labels:
        app: "finalcheckcluster-5b05"
    spec:
      containers:
        - name: "finalcheckcluster-5b05"
          image: "finalcheckcontainer.azurecr.io/finalcheckcluster"
          ports:
          - containerPort: 80