on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: finalcheckcontainer.azurecr.io
        username: ${{ secrets.acr_finalcheckcontainer_username }}
        password: ${{ secrets.acr_finalcheckcontainer_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/MenuItemsListingAPI" -f  "MenuItemsListingAPI/Dockerfile" -t finalcheckcontainer.azurecr.io/finalcheckcluster:${{ github.sha }} --label dockerfile-path=MenuItemsListingAPI/Dockerfile
        docker push finalcheckcontainer.azurecr.io/finalcheckcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_finalcheckcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep finalcheckclusterba02 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace finalcheckclusterba02`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: finalcheckclusterba02
        container-registry-url: finalcheckcontainer.azurecr.io
        container-registry-username: ${{ secrets.acr_finalcheckcontainer_username }}
        container-registry-password: ${{ secrets.acr_finalcheckcontainer_password }}
        secret-name: finalcheckcldockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: finalcheckclusterba02
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          finalcheckcontainer.azurecr.io/finalcheckcluster:${{ github.sha }}
        imagepullsecrets: |
          finalcheckcldockerauth
